# Generated by Django 4.0.5 on 2022-06-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(db_index=True, max_length=7, unique=True, verbose_name='Номер заказа')),
                ('price', models.FloatField(verbose_name='Стоимость, $')),
                ('rub_price', models.FloatField(verbose_name='Стоимость, RUB')),
                ('delivery_date', models.DateField(verbose_name='Срок доставки')),
            ],
            options={
                'ordering': ['delivery_date'],
            },
        ),
    ]
