# Generated by Django 4.0.5 on 2022-06-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AlterField(
            model_name='order',
            name='article',
            field=models.CharField(db_index=True, max_length=7, primary_key=True, serialize=False, unique=True,
                                   verbose_name='Номер заказа'),
        ),
    ]
